version: '3.4'

services:
  testservice:
    image: ${DOCKER_REGISTRY-}testservice
    build:
      context: .
      dockerfile: testservice/Dockerfile
    hostname: testservice
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001:80"

  testgateway:
    image: ${DOCKER_REGISTRY-}testgateway
    build:
      context: .
      dockerfile: testgateway/Dockerfile
    links:
      - testservice:testservice
    depends_on:
      - testservice
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"

